version: '2'
services:    
  postgresdb:
    image: "harshals/mypostgres:1.4"
    container_name: postgresdb
    volumes:
      - 'mariadb_data_sticky_test:/var/lib/postgresql/data'
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=mypguser
      - POSTGRES_DB=flktstdb
  pgwriter:
    image: "harshals/postgreswriter:1.3"
    container_name: "pgwriter"
    links:
      - "postgresdb:postgres"
    depends_on:
      - postgresdb
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=mypguser
      - POSTGRES_DB=flktstdb
      - POSTGRES_TABLE=flockertab
      - POSTGRES_HOST=postgres
  pgreader:
    image: "sghintala/postgresread:latest"
    container_name: "pgreader"
    links:
      - "postgresdb:postgres"
    volumes:
      - "/mariadb_data:/var/log"
    depends_on:
      - postgresdb
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=mypguser
      - POSTGRES_DB=flktstdb
      - POSTGRES_TABLE=flockertab
      - POSTGRES_HOST=postgres
  web:
    restart: always
    container_name: "web"
    image: "harshals/web:1.0"
    expose:
      - "8000"
    ports:
      - "8000:8000"
    links:
      - "postgresdb:postgres"
    depends_on:
      - pgwriter
    volumes:
      - /ngnix:/usr/src/app/static
    env_file: ./config/.env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

